map_update_interval: 2.0
maxUrange: 9.5
sigma: 0.01
kernelSize: 1
lstep: 0.05
astep: 0.035
iterations: 5
lsigma: 0.01
ogain: 3.0
lskip: 0
minimumScore: 150
srr: 0.1
srt: 0.2
str: 0.1
stt: 0.2
linearUpdate: 0.3
angularUpdate: 0.1
temporalUpdate: 0.2
resampleThreshold: 0.5
particles: 40
xmin: -10.0
ymin: -10.0
xmax: 10.0
ymax: 10.0
delta: 0.05
llsamplerange: 0.01
llsamplestep: 0.01
lasamplerange: 0.005
lasamplestep: 0.005
